name: calculator-publish-image
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  publish-image:
    name: publish image to docker repository
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'ashutoshahitan'
          password: 'dockerhub'

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ashutoshahitan/repo:latest
